# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b159be3cde80c3c6b1ae1fdf1091d2808f3a5aff35c53751f0662d396b99c6573499f1b3af0d5f583e0175f7b45473c92f362d1db6a1e8a61b799b388c676c86

test:
  secret_key_base: 5daf0e3cd2af92b15998c7315ea19e31305b414fe375cb22745a4e99bafa25f2d0cc60424c7a4521859054f997da7696609a4b8cff561ed9d2ac8e76a473496a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
